### ISSUE TITLE
Allow use with wildfly-preview

### ISSUE THREAD

**Issue by gesker** [wildfly-extras/wildfly-datasources-galleon-pack#105]
It would be very useful if wildfly-datasources-galleon-pack could be used with wildfly-**preview**.

Perhaps wildfly-datasources-galleon-pack does not need to reference or depend on wildfly-ee-galleon-pack which targets EE 8? Or, perhaps a parallel wildfly-**preview**-datasources-galleon-pack is needed? Or, perhaps there could be a preview flavor that could be referenced with a maven classifier?

Also, thank you for creating and maintaining this wildfly-datasources-galleon-pack. It works very nicely with the wildfly-jar-maven-plugin and this galleon-pack together the wildfly-jar:dev-watch makes for a nice developer experience. The combination, I think, will be very helpful in preparing for Jakarta 10 and even sooner in targeting applications for Jakarta 9.1 on WildFly.

**Comment by jfdenise** [comment]
@gesker , release 2.1.1.Final introduces a new feature-pack usable with wildfly Preview.Thank-you for your report.
