### ISSUE TITLE
Add new datasource parameter for the attribute 'idle-timeout-minutes'

### ISSUE THREAD

**Issue by thectrltab** [wildfly-extras/wildfly-datasources-galleon-pack#113]
Hello, 

Firewall timeout for idle-connections may sever a connection. This can cause JDBC applications to hang while waiting for a connection. 
For these scenarios the attribute [idle-timeout-minutes](https://docs.wildfly.org/26/wildscribe/subsystem/datasources/data-source/ExampleDS/index.html#attr-idle-timeout-minutes) is usually used.

If i'm not mistaken i think this is currently not supported.

Thanks for your time.

**Comment by jfdenise** [comment]
@thectrltab , PR opened to fix this issue: https://github.com/wildfly-extras/wildfly-datasources-galleon-pack/pull/120
Will be fixed in next wildfly-datasources galleon-pack.

**Comment by thectrltab** [comment]
@jfdenise thanks!

I close the issue.
