### ISSUE TITLE
Upgrade Oracle JDBC Driver

### ISSUE THREAD

**Issue by Jorelia** [wildfly-extras/wildfly-datasources-galleon-pack#135]
Hello Team,

Could you please upgrade the Oracle JDBC driver as it was moved  and because we cannot upgrade the driver through the mechanism of <overridden-server-artifacts> as the GAV is not the same. Thank you a lot team.
Best regard,
JA

From:
            <version.com.oracle.ojdbc8>19.3.0.0</version.com.oracle.ojdbc8>

            <dependency>
                <groupId>com.oracle.ojdbc</groupId>
                <artifactId>ojdbc8</artifactId>
                <version>${version.com.oracle.ojdbc8}</version>
            </dependency>

To:
```
            <dependency>
                <groupId>com.oracle.database.jdbc</groupId>
                <artifactId>ojdbc8</artifactId>
                <version>21.5.0.0</version>
                <scope>provided</scope>
            </dependency>
```

**Comment by jfdenise** [comment]
Fixed in 3.0.0.Final, changed GAV and upgrade to 19.3.0.0
