### ISSUE TITLE
Improve community experience

### ISSUE THREAD

**Issue by jfdenise** [wildfly-extras/wildfly-datasources-galleon-pack#158]
Need contributing, code of conduct, security, codeowners.

**Comment by cam-rod** [comment]
Security,md added in [da8e2b3](https://github.com/wildfly-extras/wildfly-datasources-galleon-pack/commit/da8e2b3aec192e414ea61f6018cc21ce88cce39c).

**Comment by jfdenise** [comment]
All has been added except code of conduct for which we have no clear content yet.
