### ISSUE TITLE
Need help in how to configure datasource in wildfly bootable jar

### ISSUE THREAD

**Issue by ammuvisalakshi** [wildfly-extras/wildfly-datasources-galleon-pack#18]
Hello,

I am setting up wildfly bootable jar and wanted to configure a datasource. Looking out for some examples oon how to configure this.

Thanks for your help.

**Comment by jfdenise** [comment]
Hi @ammuvisalakshi , we have a bootable JAR example that covers your case: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/master/examples/postgresql

**Comment by ammuvisalakshi** [comment]
Hello @jfdenise ,

I am not very familiar with openshift, have never worked on it.

I have actually got jaxrs project working from the examples folder. My next step is to have this project connected to existing oracle datasource. Also could you please help me understand how to have this datasource keep connected based on the environements. please share any documentations links you have.

Thank you very much.

**Comment by jfdenise** [comment]
You are not forced to use openshift. The README covers openshift but you can build a bootable jar to run on bare-metal.
Just call: mvn clean package. It will create a bootable JAR that use the same env variables (POSTGRESQL_USER, ...) to connect to a postgresql server.
You can adjust the example to use oracle. Replace: postgresql-datasource with oracle-datasource in pom.xml, then update the env variables:
POSTGRESQL_USER ==> ORACLE_USER, ...
Hope that helps.
JF

**Comment by jfdenise** [comment]
@ammuvisalakshi , any update? If you manged to get started, let me know that I close this issue.

**Comment by ammuvisalakshi** [comment]
@jfdenise yeah I got it working, Thank you !! Sorry for the late reply.
