### ISSUE TITLE
Support for Microsoft Sql Server

### ISSUE THREAD

**Issue by RowanSonder** [wildfly-extras/wildfly-datasources-galleon-pack#29]
Is there a galleon layer for Microsoft Sql Server anywhere? If not please can it be added.

**Comment by jfdenise** [comment]
@RowanSonder thank-you for your report. The SQL Server driver exists for JRE8 and JRE11. Just curious, which one do you plan to be using?

**Comment by RowanSonder** [comment]
@jfdenise I'm using JRE8

**Comment by mxw589** [comment]
Hi, was wondering if there was any timeline on this addition. Would be great!

**Comment by jmesnil** [comment]
@mxw589 we are planning soon a major release of this feature pack that will bring support for MariaDB and Microsoft Sql Server (tracked by #32)
